apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-java-springboot-jottdhty
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-java-springboot-jottdhty 
  name: backend-tests-java-springboot-jottdhty
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-java-springboot-jottdhty 
